AWSTemplateFormatVersion: '2010-09-09'

Resources:

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda-api-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: funcion-test-ci
      Runtime: nodejs20.x
      Handler: index.handler
      Timeout: 15
      Role: !GetAtt LambdaRole.Arn
      Code:
        ZipFile: |
          exports.handler = async () => {
            await new Promise(r => setTimeout(r, 3000));
            return {
              statusCode: 200,
              body: JSON.stringify({ message: "OK desde CI/CD" })
            };
          };

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: lambda-http-api
      ProtocolType: HTTP

  LambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt LambdaFunction.Arn
      PayloadFormatVersion: "2.0"

  Route:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: GET /test
      Target: !Sub integrations/${LambdaIntegration}

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: prod
      AutoDeploy: true

  Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com