name: Deploy Lambda Direct

on:
  push:
    branches:
      - labs-03

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Zip code
      run: zip function.zip labs/labs-03-pipelines-github-cloud/workflows/lab-03.1/index.js

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-2

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name FuncionTest1 \
          --zip-file fileb://function.zip

    - name: Invoke Lambda
      run: |
        aws lambda invoke \
          --function-name FuncionTest1 \
          response.json

    - run: cat response.json